name: Build ReZeroGram

on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем файлы
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Устанавливаем Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Создаем ключи Telegram API
        run: |
          echo "APP_ID=39700964" > API_KEYS
          echo 'APP_HASH="48075269202b86ee34896583ed6adf90"' >> API_KEYS
          echo 'MAPS_V2_API=""' >> API_KEYS

      - name: Генерация Keystore
        run: |
          mkdir -p TMessagesProj/config
          keytool -genkeypair -v \
            -keystore TMessagesProj/config/release.jks \
            -alias rezero \
            -keyalg RSA \
            -keysize 2048 \
            -validity 36500 \
            -storepass rezero2024 \
            -keypass rezero2024 \
            -dname "CN=ReZeroGram, OU=Dev, O=ZeroGram, L=Internet, ST=Web, C=RU"

      - name: Настройка Gradle
        run: chmod +x gradlew

      - name: Сборка Release APK
        run: |
          ./gradlew assembleAfatRelease --no-daemon --stacktrace
        env:
          GRADLE_OPTS: "-Xmx8g -Xss32m -Dfile.encoding=UTF-8"

      - name: Сохраняем готовый APK
        uses: actions/upload-artifact@v4
        with:
          name: ReZeroGram-APK
          path: 'TMessagesProj/build/outputs/apk/**/*.apk'
